version:  '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
  mongodb:
    image:  mongo
    ports: 
      - 27017:27017
    environment:
      - ME_MONGO_INITDB_ROOT_USERNAME= admin
      - ME_MONGO_INITDB_ROOT_PASSWORD= password